import { expect, test } from '@playwright/test'

async function signIn(page: import('@playwright/test').Page) {
  await page.goto('/')
  await page.getByLabel('Email or phone').fill('member@sports-center.local')
  await page.getByLabel('Password').fill('ChangeMe123!')
  await page.getByRole('button', { name: /Continue/ }).click()
  await expect(page.getByRole('heading', { name: 'Chọn lớp cho buổi tập tiếp theo.' })).toBeVisible()
}

test('member registers a different-sport package and sees immutable membership history', async ({ page }) => {
  await signIn(page)
  await page.getByRole('button', { name: 'Gói tập' }).click()
  await expect(page.getByRole('heading', { name: 'Chọn gói tập phù hợp.' })).toBeVisible()
  await expect(page.getByText(/Thanh toán được thực hiện bên ngoài ứng dụng/)).toBeVisible()
  const gymPackage = page.getByRole('button', { name: /Gói Gym Tiêu Chuẩn 1 Tháng/ })
  await gymPackage.focus()
  await gymPackage.press('Enter')
  await expect(gymPackage).toHaveAttribute('aria-pressed', 'true')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false)
  const registerButton = page.getByRole('button', { name: 'Đăng ký gói' })
  await expect(registerButton).toBeVisible()
  const requestStartedAt = Date.now()
  const registrationResponsePromise = page.waitForResponse((response) => response.url().endsWith('/api/memberships') && response.request().method() === 'POST')
  await registerButton.focus()
  await registerButton.press('Enter')
  const registrationResponse = await registrationResponsePromise
  expect(registrationResponse.status()).toBe(201)
  const registration = await registrationResponse.json() as { packageName: string; sportType: string; durationDays: number; listedPrice: number; startDate: string; endDate: string }
  expect(registration).toMatchObject({ packageName: 'Gói Gym Tiêu Chuẩn 1 Tháng', sportType: 'Gym', durationDays: 30, listedPrice: 500000 })
  expect(Date.parse(registration.startDate)).toBeGreaterThanOrEqual(requestStartedAt - 5000)
  expect(Date.parse(registration.startDate)).toBeLessThanOrEqual(Date.now())
  expect(Date.parse(registration.endDate) - Date.parse(registration.startDate)).toBe(30 * 24 * 60 * 60 * 1000)
  await expect(page.getByRole('heading', { name: 'Membership của tôi.' })).toBeVisible()
  await expect(page.getByRole('status')).toContainText('đã có hiệu lực ngay')
  await expect(page.getByRole('status')).toContainText('Thanh toán được thực hiện bên ngoài ứng dụng')
  await page.setViewportSize({ width: 1440, height: 1000 })
  const memberships = page.locator('.history-groups')
  await expect(memberships.getByText('Gói Gym Tiêu Chuẩn 1 Tháng')).toBeVisible()
  await expect(memberships.getByText('Gói Yoga Chuyên Sâu 3 Tháng')).toBeVisible()
  await expect(memberships.getByText('500.000 đ')).toBeVisible()
  await expect(memberships.getByText('1.800.000 đ')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Membership của tôi' })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false)
  await page.getByRole('button', { name: 'Gói tập' }).click()
  await expect(page.getByRole('button', { name: /Toàn diện/ })).toBeDisabled()
  await expect(page.getByRole('heading', { name: 'Chọn gói tập phù hợp.' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false)
})
